const URL = "https://api.uphold.com/v0/ticker/";
const NOT_FOUND = 'not_found';
const TOO_MANY_REQUESTS = 'too_many_requests';
const INCREASED_FETCH_INTERVAL = 5000; //ms
const DEFAULT_CURRENCY_PAIR = "BTC-USD";
const DEFAULT_FETCH_INTERVAL = 5000; //ms
const MIN_FETCH_INTERVAL = 1000; //ms
const DEFAULT_PRICE_CHANGE_THRESHOLD = 0.01; //percentage
const MIN_PRICE_CHANGE_THRESHOLD = 0.0001; //percentage
const PRECISION_DIGITS = 4;

module.exports = { URL, NOT_FOUND, TOO_MANY_REQUESTS, INCREASED_FETCH_INTERVAL, DEFAULT_CURRENCY_PAIR, DEFAULT_FETCH_INTERVAL, MIN_FETCH_INTERVAL, 
    DEFAULT_PRICE_CHANGE_THRESHOLD, MIN_PRICE_CHANGE_THRESHOLD, PRECISION_DIGITS };