version: '3.8'
services:
  bot:
    build: ./bot
    image: uphold-bot
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env-bot
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./bot:/app
      - ./bot/node_modules:/app/node_modules

  db:
    image: postgres
    env_file:
      - ./.env-database
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/create.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local